<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\UserController;
use Illuminate\Http\JsonResponse;

class AdminController extends UserController
{
    public function listUser($id)
    {
        $user = auth()->user();
        if ($user->role === 'ROLE_ROOT') {
            return parent::listUser($id); // TODO: Change the autogenerated stub
        }
        return response()->json(['message' => 'User is not an administrator!']);
    }

    public function listUsers(): array
    {
        $user = auth()->user();
        if ($user->role === 'ROLE_ROOT') {
            return parent::listUsers(); // TODO: Change the autogenerated stub
        }
        return ['message' => 'User is not an administrator!'];
    }

    public function delete($id): JsonResponse
    {
        $user = auth()->user();
        if ($user->role === 'ROLE_ROOT') {
            return parent::delete($id); // TODO: Change the autogenerated stub
        }
        return response()->json(['message' => 'User is not an administrator!']);
    }

    public function update(Request $request): JsonResponse
    {
        $user = auth()->user();
        if ($user->role === 'ROLE_ROOT') {
            return parent::update($request); // TODO: Change the autogenerated stub
        }
        return response()->json(['message' => 'User is not an administrator!']);
    }
}
